export default {
  aliases: [],
  jpeg: { quality: 80, interlace: true },
  webp: { enabled: 'ALLOW', convert: true, convert_animated: false },
  webp_png: { enabled: 'ALLOW' },
  svg: { do_not_resize: 1 },
  mapping: { pref_geo: 'FRANCE', pref_hexa: null },
  elastic: { failover_retries: null, failover_on_404: null },
  cache: { output_max_age: 2592000, output_s_max_age: 31536000 },
  restrictions: { paths: null },
  choices: {
    default_rotate: true,
    default_same_if_lower: null,
    missing_img_behavior: 'returns_200_1x1_gif',
    whitelist_img_behavior: 'W_HTTP_406',
    whitelist_ultrafast: 'off',
  },
  refresh_master_images: { enabled: null, period: 2592000, method: null },
  allowed_domains: [],
  png: { png_lossy: false, quality: 50 },
  origin_process: {
    keep_exif: false,
    jpg_icc: {
      keep: false,
      if_big_go_srgb: { enabled: false, trigger_size: 0 },
    },
  },
  origin_prefix: {
    method: 'EVERYTIME',
    url: 'https://boardwaves-com.onrender.com/img/',
  },
  origin_behavior: { request_headers: {} },
  avif: { enabled: 'NOT_ALLOW' },
  gif: { lossy_animated: false },
  proxy_everything_that_is_not_cloudimage_processable_extension: 0,
  rules: [{ match: '', comment: '', params: '' }],
  advanced: { proxy_connstring: '' },
  presets: [
    {
      name: 'feed',
      desc: '',
      params: {
        bg_blur: '30',
        bg_img_fit: '1',
        bg_opacity: '0.5',
        func: 'fit',
        h: '500',
        q: '80',
        w: '500',
      },
    },
    {
      name: 'mini',
      desc: '',
      params: { blur: '30', func: 'cropfit', h: '50', w: '50' },
    },
  ],
  cnames: [''],
  cnames_tls_validation: [],
  storage_providers: {
    aws_s3: null,
    own: [],
    azure_blob: null,
    google_cloud: null,
  },
}
